version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    restart: always
    ports:
      - 1433
    volumes:
      - ./storage/mssqldata:/var/opt/mssq
      - ./config/mssql/init.sql:/init.sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dev@2021
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/public
    links:
      - graphql_v1
    depends_on:
      - graphql_v1
    ports:
      - 8080:80
  redis:
    image: redis:latest
    container_name: redis
    restart: always
  graphql_v1:
    container_name: graphql_v1
    build:
      context: ./server/graphql
    command: yarn dev
    environment:
      - SQL_PROJECT_TABLE=myapp
      - SQL_ROOT_USER=SA
      - SQL_ROOT_PASSWORD=Dev@2021
    depends_on:
      - mssql
      - redis
    links:
      - mssql
      - redis
    volumes:
      - /app/node_modules
      - ./server/graphql:/usr/app
    ports:
      - 3002
