version: '3'

services:
  postgresql-master:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_DATABASE=my_database
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - ALLOW_EMPTY_PASSWORD=yes
  postgresql-slave:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/public
    links:
      - graphql_v1
    depends_on:
      - graphql_v1
    ports:
      - 8080:80
  redis:
    image: redis:latest
    container_name: redis
    restart: always
  graphql_v1:
    container_name: graphql_v1
    environment:
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_DATABASE=my_database
    build:
      context: ./server/graphql
    command: yarn dev
    depends_on:
      - postgresql-master
      - redis
    links:
      - postgresql-master
      - redis
    volumes:
      - /app/node_modules
      - ./server/graphql:/usr/app
    ports:
      - 3002
volumes:
  postgresql_master_data:
    driver: local
