version: '3'

services:
  mongodb:
    image: mongo:4.0-xenial
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./mongo/data:/data/db
    restart: always
    command: --bind_ip_all --replSet rs0 --oplogSize 128
  mongodb_replica_1:
    image: mongo:4.0-xenial
    container_name: mongodb_replica_1
    hostname: mongodb_replica_1
    volumes:
      - ./mongo/data_1:/data/db
    restart: always
    command: --bind_ip_all --replSet rs0 --oplogSize 128
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/public
    links:
      - graphql_v1
    depends_on:
      - graphql_v1
    ports:
      - 8080:80
  redis:
    image: redis:latest
    container_name: redis
    restart: always
  graphql_v1:
    container_name: graphql_v1
    build:
      context: .
    command: yarn dev
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - mongodb_replica_1
      - redis
    volumes:
      - /app/node_modules
      - ./server/graphql:/usr/app
    ports:
      - 3002
